name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.m2/repository"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '11'
    - run: cd h2
    - run: echo $JAVA_OPTS
    - run: export JAVA_OPTS=-Xmx512m
    - run: "./build.sh jar testTravis"
  test_2:
    runs-on: # this agent type is not supported: [trusty]
             ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.m2/repository"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '8'
    - run: cd h2
    - run: echo $JAVA_OPTS
    - run: export JAVA_OPTS=-Xmx512m
    - run: "./build.sh jar testTravis"
