name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
env:
  TERM: dumb
  DEFAULT_TIMEOUT_MILLIS: '300'
  DEFAULT_NO_SIGNALS_TIMEOUT_MILLIS: '200'
  PUBLISHER_REFERENCE_GC_TIMEOUT_MILLIS: '300'
jobs:
  test:
    runs-on: # this agent type is not supported: [[{"dist"=>"trusty"}]]
             ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.gradle"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '8'
#     # This item has no matching transformer
#     - hostname: rs-jvm
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: export GRADLE_OPTS=-Xmx1024m
    - run: "./gradlew -version"
    - run: "./gradlew check"
  test_2:
    runs-on: # this agent type is not supported: [[{"dist"=>"trusty"}]]
             ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.gradle"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '9'
#     # This item has no matching transformer
#     - hostname: rs-jvm
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: export GRADLE_OPTS=-Xmx1024m
    - run: "./gradlew -version"
    - run: "./gradlew check"
