name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v4.0.0
      with:
        cache: npm
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: npm install
    - run: npm test
    - uses: rectalogic/notify-irc@v1
      with:
        server: irc.freenode.org
        port: 6697
        channel: socket.io
        nickname: Default nickname
        message: Default message
    strategy:
      matrix:
        node_js:
        - '10'
        - '12'
        - '14'
