name: Android CI

on:
  push:
    branches:
      - master
      - 'v*.*.*'
      - 'v*.*.*-beta*'
      - 'v*.*.*-rc*'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adoptopenjdk'

  clean:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean project
        run: ./gradlew clean

  assembleDebug:
    runs-on: ubuntu-latest
    needs: clean

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assemble Debug APK
        run: ./gradlew demo:assembleDebug

  testDebugUnitTest:
    runs-on: ubuntu-latest
    needs: assembleDebug

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: ./gradlew cameraview:testDebugUnitTest

  connectedCheck:
    runs-on: ubuntu-latest
    needs: testDebugUnitTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Connected Tests
        run: ./gradlew cameraview:connectedCheck

  mergedCoverageReport:
    runs-on: ubuntu-latest
    needs: connectedCheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Merged Coverage Report
        run: ./gradlew cameraview:mergedCoverageReport

  generateJavadoc:
    runs-on: ubuntu-latest
    needs: mergedCoverageReport

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Javadoc
        run: ./gradlew cameraview:javadoc

  uploadCoverage:
    runs-on: ubuntu-latest
    needs: generateJavadoc

    steps:
      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash) -s "*/build/reports/mergedCoverageReport/"
