name: CI Build

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the action
  pull_request:
    branches:
      - main  # Adjust this to the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-20.04  # Equivalent to 'dist: xenial' (Ubuntu 16.04 is EOL, so Ubuntu 20.04 is used)

    strategy:
      matrix:
        jdk:
          - adoptopenjdk-8
          - amazon-corretto-8
          - openjdk-9
          - openjdk-11
          - openjdk-12
          - openjdk-13
        # You can add other JDKs or versions as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adoptopenjdk'  # This matches your JDK distribution choices, adjust if needed
          
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build with Maven
        run: |
          /usr/local/maven/bin/mvn verify -B
