name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: node_modules
        key: "${{ runner.os }}-path"
    - uses: actions/setup-node@v4.0.0
      with:
        cache: npm
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: npm install
    - run: npm run lint
    - run: npm run cover
    - run: npm run coveralls
#     # This item has no matching transformer
#     - email: false
