name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
    - master
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TOXENV: py33
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.3'
    - run: pip install -U tox
    - run: tox
  test_2:
    runs-on: ubuntu-latest
    env:
      TOXENV: py34
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.4'
    - run: pip install -U tox
    - run: tox
  test_3:
    runs-on: ubuntu-latest
    env:
      TOXENV: py35
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.5'
    - run: pip install -U tox
    - run: tox
  test_4:
    runs-on: ubuntu-latest
    env:
      TOXENV: py36
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.6'
    - run: pip install -U tox
    - run: tox
